# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0004_review_rides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_pic', models.ImageField(blank=True, upload_to='driver/')),
                ('car_make', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('reg_numb', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
