# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_auto_20171206_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
